// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbsaIaYs0bzrei4Q1fPmtw0Uzu0MBJc0',
    appId: '1:954213469457:web:e232bb439b27b10ac0d0b0',
    messagingSenderId: '954213469457',
    projectId: 'chatxz',
    authDomain: 'chatxz.firebaseapp.com',
    storageBucket: 'chatxz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43nlKYJKKcLbttCRrU6TkMmFI2zdzHdc',
    appId: '1:954213469457:android:5b457db9fad19d25c0d0b0',
    messagingSenderId: '954213469457',
    projectId: 'chatxz',
    storageBucket: 'chatxz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBybz94ngTbiHXPMa6ua80kOojKIcTHmmU',
    appId: '1:954213469457:ios:1abcdea783347728c0d0b0',
    messagingSenderId: '954213469457',
    projectId: 'chatxz',
    storageBucket: 'chatxz.appspot.com',
    iosClientId: '954213469457-s3g8nmboifd7knod53afudtj0tosm6km.apps.googleusercontent.com',
    iosBundleId: 'com.devkotes.chatx',
  );
}
